# Chp 3 Introduction to ML

Decision tree construction relies on recursion, where a function calls itself on smaller versions of the problem until reaching a stopping condition. For example, the factorial function can be defined recursively:

```python
𝑛! = 𝑛 × (𝑛−1)!
```

In the same way, decision trees build subtrees by applying the same process recursively on subsets of the training data, until reaching a leaf node.


In [5]:
# Factorial
def factorial(n):
    if (n<=1):
        return 1
    else:
        print("Current value of n:",n)
        return n*factorial (n-1)
factorial(5)


Current value of n: 5
Current value of n: 4
Current value of n: 3
Current value of n: 2


120

# Chp 4 Experiments with Classical Models

## Iris

The iris dataset contains four continuous features—sepal length, sepal width, petal length, and petal width—and three classes corresponding to iris species. It has 150 samples, 50 per class. Using PCA augmentation, we expand the dataset to 1,200 training samples while keeping the same test set.

In [1]:
# Iris Experiments
import numpy as np
from sklearn.neighbors import NearestCentroid, KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC 
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

# Load data
def load_iris_data():
    """Load and prepare the iris dataset"""
    iris = load_iris()
    x = iris.data  # shape (150,4)
    y = iris.target

    # Shuffle to match train/test splits
    np.random.seed(42)  # for reproducibility
    indices = np.random.permutation(len(x))
    x = x[indices]
    y = y[indices]
    return x, y

def create_augmented_data(x_train, y_train, x_test, y_test):
    """Create augmented data by adding noise and scaling"""
    # Add noise to training data
    np.random.seed(42)
    noise = np.random.normal(0, 0.1, x_train.shape)  # Gaussian noise
    xa_train = x_train + noise
    ya_train = y_train.copy()

    # Scale the features
    scaler = StandardScaler()
    xa_train = scaler.fit_transform(xa_train)
    xa_test = scaler.transform(x_test)

    return xa_train, ya_train, xa_test, y_test

def run(x_train, y_train, x_test, y_test, clf):
    clf.fit(x_train, y_train)  # Fixed
    predictions = clf.predict(x_test)
    acc = clf.score(x_test, y_test)
    print("\tpredictions:", predictions)
    print("\tactual labels:", y_test)
    print(f"\taccuracy score: {acc:.4f}")
    print()

def main():
    # Load iris data
    x, y = load_iris_data()

    # Split data (120 for training, 30 for testing)
    N = 120
    x_train, x_test = x[:N], x[N:]
    y_train, y_test = y[:N], y[N:]

    # Create augmented data
    xa_train, ya_train, xa_test, ya_test = create_augmented_data(x_train, y_train, x_test, y_test)

    print("Nearest centroid:")
    run(x_train, y_train, x_test, y_test, NearestCentroid())

    print("k-NN classifier (k=3):")
    run(x_train, y_train, x_test, y_test, KNeighborsClassifier(n_neighbors=3))

    print("Naive Bayes classifier (Gaussian):")
    run(x_train, y_train, x_test, y_test, GaussianNB())

    print("Naive Bayes classifier (Multinomial):")
    run(x_train, y_train, x_test, y_test, MultinomialNB())

    print("Decision tree classifier:")
    run(x_train, y_train, x_test, y_test, DecisionTreeClassifier())

    print("Random forest classifier (estimators=5):")
    run(xa_train, ya_train, xa_test, ya_test, RandomForestClassifier(n_estimators=5))

    print("SVM (linear, C=1.0):")
    run(xa_train, ya_train, xa_test, ya_test, SVC(kernel="linear", C=1.0))

    print("SVM (RBF, C=1.0, gamma=0.25):")
    run(xa_train, ya_train, xa_test, ya_test, SVC(kernel="rbf", C=1.0, gamma=0.25))

    print("SVM (RBF, C=1.0, gamma=0.001, augmented):")
    run(xa_train, ya_train, xa_test, ya_test, SVC(kernel="rbf", C=1.0, gamma=0.001))

    print("SVM (RBF, C=1.0, gamma=0.001, original):")
    run(x_train, y_train, x_test, y_test, SVC(kernel="rbf", C=1.0, gamma=0.001))

if __name__ == "__main__":
    main()


Nearest centroid:
	predictions: [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 2 2 2 1 2 1 1 1 2 0 1 1 0 1 2]
	actual labels: [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1 2]
	accuracy score: 0.9000

k-NN classifier (k=3):
	predictions: [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 1 0 1 2]
	actual labels: [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1 2]
	accuracy score: 0.9667

Naive Bayes classifier (Gaussian):
	predictions: [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 2 2 2 1 2 1 1 2 2 0 1 1 0 1 2]
	actual labels: [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1 2]
	accuracy score: 0.9333

Naive Bayes classifier (Multinomial):
	predictions: [1 0 1 1 0 1 2 2 0 1 2 1 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1 2]
	actual labels: [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1 2]
	accuracy score: 0.9667

Decision tree classifier:
	predictions: [1 0 1 1 0 1 2 2 0 1 2 1 0 2 0 1 2 2 1 2 1 1 2 2 0 1 1 0 1 2]
	actual labels: [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1

### Implementing a Nearest-Centroid Classifier

Even without sklearn, we can quickly implement a nearest-centroid classifier for the iris dataset. The process involves calculating the per-feature means (centroids) of each class from the training samples. This is all that is needed to "train" the model. Predictions are made by computing the Euclidean distance from each test sample to the three centroids, assigning the sample to the class with the nearest centroid. 

In [3]:
import numpy as np
from sklearn.datasets import load_iris

def load_iris_data():
    """Load and prepare the iris dataset"""
    iris = load_iris()
    x = iris.data
    y = iris.target
    
    # Shuffle the data to match typical train/test splits
    np.random.seed(42)  # For reproducibility
    indices = np.random.permutation(len(x))
    x = x[indices]
    y = y[indices]
    
    return x, y

def centroids(x, y):
    """Compute centroids for each class"""
    c0 = x[y == 0].mean(axis=0)
    c1 = x[y == 1].mean(axis=0)
    c2 = x[y == 2].mean(axis=0)
    return [c0, c1, c2]

def predict(c0, c1, c2, x):
    """Predict class by nearest centroid"""
    p = np.zeros(x.shape[0], dtype="uint8")
    for i in range(x.shape[0]):
        d = [
            ((c0 - x[i])**2).sum(),  # distance to c0
            ((c1 - x[i])**2).sum(),  # distance to c1
            ((c2 - x[i])**2).sum()   # distance to c2
        ]
        p[i] = np.argmin(d)  # index of nearest centroid
    return p

def main():
    # Load iris data using sklearn
    x, y = load_iris_data()
    
    # Split data (120 for training, rest for testing)
    N = 120  # total data = 150
    x_train, x_test = x[:N], x[N:]
    y_train, y_test = y[:N], y[N:]
    
    # Calculate centroids and make predictions
    c0, c1, c2 = centroids(x_train, y_train)
    p = predict(c0, c1, c2, x_test)
    
    # Calculate accuracy
    nc = np.sum(p == y_test)
    nw = np.sum(p != y_test)
    acc = nc / (nc + nw)
    
    print("predicted:", p)
    print("actual   :", y_test)
    print("test accuracy = %0.4f" % acc)

if __name__ == "__main__":
    main()


predicted: [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 2 2 2 1 2 1 1 1 2 0 1 1 0 1 2]
actual   : [1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1 1 2 2 0 1 2 0 1 2]
test accuracy = 0.9000


## Breast Cancer

The breast cancer dataset contains 569 samples, each with 30 continuous features, including 212 malignant and 357 benign cases. Before training, we normalize the dataset by subtracting the mean and dividing by the standard deviation for each feature. Normalization ensures all features are on a similar scale, improving performance for many models.

Using an 80/20 train-test split (455 training samples and 114 test samples), we train nine classifiers: nearest centroid, k-NN, naive Bayes, decision tree, random forest (two variants), linear SVM, and RBF SVM. For the SVMs, we set the margin constant C to the default 1.0, and γ for the RBF kernel to 0.0333 (1/30).


In [5]:
# BC experiments
import numpy as np
from sklearn.neighbors import NearestCentroid, KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC 
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

def load_breast_cancer_data():
    """Load and prepare the breast cancer dataset with standardization"""
    cancer = load_breast_cancer()
    x = cancer.data
    y = cancer.target
    
    # Shuffle the data for better training
    np.random.seed(42)  # for reproducibility
    indices = np.random.permutation(len(x))
    x = x[indices]
    y = y[indices]

    # Normalize the features (standardization: mean=0, std=1)
    scaler = StandardScaler() 
    x_standardized = scaler.fit_transform(x)

    return x_standardized, y

def run(x_train, y_train, x_test, y_test, clf):
    clf.fit(x_train, y_train)
    print("\tscore = %0.4f" % clf.score(x_test, y_test))
    print()

def main():
    # Load breast cancer data with standardization
    x, y = load_breast_cancer_data()
    
    # Split data (455 for training, rest for testing)
    N = 455 
    x_train, x_test = x[:N], x[N:]
    y_train, y_test = y[:N], y[N:]
    
    print(f"Dataset info: {len(x)} samples, {x.shape[1]} features")
    print(f"Training set: {len(x_train)} samples")
    print(f"Test set: {len(x_test)} samples")
    print(f"Class distribution - Training: {np.bincount(y_train)}, Test: {np.bincount(y_test)}")
    print()

    print("Nearest centroid:")
    run(x_train, y_train, x_test, y_test, NearestCentroid())

    print("k-NN classifier (k=3):")
    run(x_train, y_train, x_test, y_test, KNeighborsClassifier(n_neighbors=3))

    print("k-NN classifier (k=7):")
    run(x_train, y_train, x_test, y_test, KNeighborsClassifier(n_neighbors=7))

    print("Naive Bayes classifier (Gaussian):")
    run(x_train, y_train, x_test, y_test, GaussianNB())

    print("Decision tree classifier:")
    run(x_train, y_train, x_test, y_test, DecisionTreeClassifier())

    print("Random forest classifier (estimators=5):")
    run(x_train, y_train, x_test, y_test, RandomForestClassifier(n_estimators=5))

    print("Random forest classifier (estimators=50):")
    run(x_train, y_train, x_test, y_test, RandomForestClassifier(n_estimators=50))

    print("SVM (linear, C=1.0):")
    run(x_train, y_train, x_test, y_test, SVC(kernel="linear", C=1.0))

    print("SVM (RBF, C=1.0, gamma=0.03333):")
    run(x_train, y_train, x_test, y_test, SVC(kernel="rbf", C=1.0, gamma=0.03333))

if __name__ == "__main__":
    main()


Dataset info: 569 samples, 30 features
Training set: 455 samples
Test set: 114 samples
Class distribution - Training: [165 290], Test: [47 67]

Nearest centroid:
	score = 0.9298

k-NN classifier (k=3):
	score = 0.9474

k-NN classifier (k=7):
	score = 0.9386

Naive Bayes classifier (Gaussian):
	score = 0.9298

Decision tree classifier:
	score = 0.9211

Random forest classifier (estimators=5):
	score = 0.9298

Random forest classifier (estimators=50):
	score = 0.9561

SVM (linear, C=1.0):
	score = 0.9649

SVM (RBF, C=1.0, gamma=0.03333):
	score = 0.9737



### Adding k-Fold Validation

To implement k-fold validation, we first select a value for k. For the breast cancer dataset with 569 samples, a balance is needed: smaller k ensures each fold has enough samples to represent the data reasonably, while larger k helps average out the effects of a “bad” split. A common choice is k = 5, giving roughly 113 samples per fold, with 80% for training and 20% for testing. The code is designed to allow easy adjustment of k.

In [11]:
# bc_kfold_fixed.py
import numpy as np
import sys
import traceback
from sklearn.neighbors import NearestCentroid, KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

def load_breast_cancer_data():
    cancer = load_breast_cancer()
    x = cancer.data
    y = cancer.target
    scaler = StandardScaler()
    x_standardized = scaler.fit_transform(x)
    return x_standardized, y

def run(x_train, y_train, x_test, y_test, clf):
    clf.fit(x_train, y_train)
    return clf.score(x_test, y_test)

def split(x, y, k, m):
    """Return x_train, y_train, x_test, y_test for k-th fold.
       Uses np.array_split so fold sizes can differ by 1 when n % m != 0.
    """
    n = x.shape[0]
    idx_folds = np.array_split(np.arange(n), m)  # list of index arrays
    test_idx = idx_folds[k]
    train_idx = np.hstack([idx_folds[i] for i in range(m) if i != k])
    return x[train_idx], y[train_idx], x[test_idx], y[test_idx]

def pp(z, k, name):
    m = z.shape[1]
    mean = z[k].mean()
    stderr = z[k].std() / np.sqrt(m)
    print("{:20s}: {:0.4f} +/- {:0.4f} | ".format(name, mean, stderr), end='')
    for i in range(m):
        print("{:0.4f} ".format(z[k, i]), end='')
    print()

def main(argv=None):
    try:
        if argv is None:
            argv = sys.argv

        # Parse folds argument if provided, otherwise default to 5
        if len(argv) >= 2:
            try:
                m = int(argv[1])
                if m < 2:
                    print("Number of folds must be >= 2. Using 5.")
                    m = 5
            except ValueError:
                print("Invalid folds argument. Using 5.")
                m = 5
        else:
            m = 5

        x, y = load_breast_cancer_data()

        if m > x.shape[0]:
            print(f"Requested {m} folds but dataset has only {x.shape[0]} samples. Reducing folds to {x.shape[0]}.")
            m = x.shape[0]

        # Shuffle
        np.random.seed(42)
        perm = np.random.permutation(len(y))
        x = x[perm]
        y = y[perm]

        print(f"Performing {m}-fold cross-validation on breast cancer dataset")
        print(f"Dataset: {x.shape[0]} samples, {x.shape[1]} features")
        print()

        classifiers = [
            ("Nearest centroid", NearestCentroid()),
            ("3-NN", KNeighborsClassifier(n_neighbors=3)),
            ("7-NN", KNeighborsClassifier(n_neighbors=7)),
            ("Naive Bayes", GaussianNB()),
            ("Decision tree", DecisionTreeClassifier()),
            ("Random forest (5)", RandomForestClassifier(n_estimators=5)),
            ("Random forest (50)", RandomForestClassifier(n_estimators=50)),
            ("SVM (linear)", SVC(kernel="linear", C=1.0))
        ]

        z = np.zeros((len(classifiers), m))

        for k in range(m):
            x_train, y_train, x_test, y_test = split(x, y, k, m)
            for i, (_, clf) in enumerate(classifiers):
                z[i, k] = run(x_train, y_train, x_test, y_test, clf)

        print("Results (mean +/- stderr | individual fold scores):")
        print("-" * 70)
        for i, (name, _) in enumerate(classifiers):
            pp(z, i, name)

    except Exception:
        print("An exception occurred — full traceback below:")
        traceback.print_exc()

if __name__ == "__main__":
    main()


Invalid folds argument. Using 5.
Performing 5-fold cross-validation on breast cancer dataset
Dataset: 569 samples, 30 features

Results (mean +/- stderr | individual fold scores):
----------------------------------------------------------------------
Nearest centroid    : 0.9315 +/- 0.0076 | 0.9561 0.9035 0.9298 0.9386 0.9292 
3-NN                : 0.9613 +/- 0.0064 | 0.9474 0.9737 0.9561 0.9825 0.9469 
7-NN                : 0.9613 +/- 0.0073 | 0.9474 0.9825 0.9737 0.9649 0.9381 
Naive Bayes         : 0.9367 +/- 0.0068 | 0.9649 0.9211 0.9386 0.9298 0.9292 
Decision tree       : 0.9280 +/- 0.0067 | 0.9298 0.9211 0.9035 0.9386 0.9469 
Random forest (5)   : 0.9508 +/- 0.0040 | 0.9386 0.9649 0.9474 0.9474 0.9558 
Random forest (50)  : 0.9666 +/- 0.0016 | 0.9649 0.9737 0.9649 0.9649 0.9646 
SVM (linear)        : 0.9719 +/- 0.0058 | 0.9561 0.9825 0.9649 0.9912 0.9646 


### Fine-Tuning the RBF Kernel SVM

For the RBF (Gaussian) kernel SVM, both C and γ must be optimized. A 2D grid search is performed:

- C uses the same range as the linear SVM.
- γ is selected from powers of two times the default 1/30, for p ∈ [–4, 3].

For each pair (C, γ), five-fold validation is performed, and the pair with the highest mean accuracy is selected. Repeated runs produce slightly different results due to randomization in the dataset ordering.

One promising combination is (C, γ) = (10, 0.00417), which achieves a grand mean accuracy of 97.70%, the highest among all models tested on the breast cancer dataset.


In [12]:
# BC RBF SVM Search
import numpy as np
from sklearn.svm import SVC 
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

def load_breast_cancer_data():
    """Load and prepare the breast cancer dataset with standardization"""
    # Load the breast cancer dataset
    cancer = load_breast_cancer()
    x = cancer.data
    y = cancer.target
    
    # Normalize the features (subtract mean and divide by std)
    scaler = StandardScaler()
    x_standardized = scaler.fit_transform(x)
    
    return x_standardized, y

def run(x_train, y_train, x_test, y_test, clf):
    clf.fit(x_train, y_train)
    return clf.score(x_test, y_test)

def split(x,y,k,m):
    ns = int(y.shape[0]/m)
    s = []
    for i in range(m):
        s.append([x[(ns*i):(ns*i+ns)], y[(ns*i):(ns*i+ns)]])
    x_test, y_test = s[k]
    x_train = []
    y_train = []
    for i in range(m):
        if (i==k):
            continue
        else:
            a,b = s[i]
            x_train.append(a)
            y_train.append(b)
    x_train = np.array(x_train).reshape(((m-1)*ns,30))
    y_train = np.array(y_train).reshape((m-1)*ns)
    return [x_train, y_train, x_test, y_test]

def main():
    m = 5 
    
    # Load breast cancer data with standardization
    x, y = load_breast_cancer_data()
    
    # Shuffle the data
    np.random.seed(42)  # For reproducibility
    idx = np.argsort(np.random.random(y.shape[0]))
    x = x[idx]
    y = y[idx]
    
    print(f"RBF SVM Hyperparameter Search using {m}-fold cross-validation")
    print(f"Dataset: {x.shape[0]} samples, {x.shape[1]} features")
    print()

    Cs = np.array([0.01,0.1,1.0,2.0,10.0,50.0,100.0])
    gs = (1./30)*2.0**np.array([-4,-3,-2,-1,0,1,2,3])
    
    print("C values:", Cs)
    print("Gamma values:", gs)
    print()
    print("Searching hyperparameters...")
    
    zmax = 0.0 
    best_scores = []
    
    for i, C in enumerate(Cs): 
        for j, g in enumerate(gs): 
            z = np.zeros(m)
            for k in range(m):
                x_train, y_train, x_test, y_test = split(x,y,k,m)
                z[k] = run(x_train, y_train, x_test, y_test, SVC(C=C,gamma=g,kernel="rbf"))
            
            mean_score = z.mean()
            if (mean_score > zmax):
                zmax = mean_score
                bestC = C 
                bestg = g 
                best_scores = z.copy()
            
            # Print progress (optional - comment out if too verbose)
            print(f"C={C:6.2f}, gamma={g:8.5f}: {mean_score:.4f} (+/- {z.std():.4f})")
    
    print()
    print("=" * 50)
    print("BEST HYPERPARAMETERS:")
    print("best C     = %0.5f" % bestC)
    print("     gamma = %0.5f" % bestg)
    print("   accuracy= %0.5f (+/- %0.5f)" % (zmax, best_scores.std()))
    print("individual fold scores:", [f"{score:.4f}" for score in best_scores])

if __name__ == "__main__":
    main()

RBF SVM Hyperparameter Search using 5-fold cross-validation
Dataset: 569 samples, 30 features

C values: [1.e-02 1.e-01 1.e+00 2.e+00 1.e+01 5.e+01 1.e+02]
Gamma values: [0.00208333 0.00416667 0.00833333 0.01666667 0.03333333 0.06666667
 0.13333333 0.26666667]

Searching hyperparameters...
C=  0.01, gamma= 0.00208: 0.6248 (+/- 0.0527)
C=  0.01, gamma= 0.00417: 0.6248 (+/- 0.0527)
C=  0.01, gamma= 0.00833: 0.6248 (+/- 0.0527)
C=  0.01, gamma= 0.01667: 0.6301 (+/- 0.0569)
C=  0.01, gamma= 0.03333: 0.6248 (+/- 0.0527)
C=  0.01, gamma= 0.06667: 0.6248 (+/- 0.0527)
C=  0.01, gamma= 0.13333: 0.6248 (+/- 0.0527)
C=  0.01, gamma= 0.26667: 0.6248 (+/- 0.0527)
C=  0.10, gamma= 0.00208: 0.8938 (+/- 0.0280)
C=  0.10, gamma= 0.00417: 0.9327 (+/- 0.0132)
C=  0.10, gamma= 0.00833: 0.9434 (+/- 0.0144)
C=  0.10, gamma= 0.01667: 0.9451 (+/- 0.0130)
C=  0.10, gamma= 0.03333: 0.9434 (+/- 0.0221)
C=  0.10, gamma= 0.06667: 0.9416 (+/- 0.0278)
C=  0.10, gamma= 0.13333: 0.9097 (+/- 0.0505)
C=  0.10, gamma= 0.

## MNIST

The final dataset examined in this chapter is the vector version of MNIST, which contains 28×28 grayscale images of handwritten digits (0–9), one per image. MNIST is a foundational dataset in machine learning and deep learning and will be used throughout the book.

MNIST has 60,000 training images and 10,000 test images, roughly balanced across the 10 digits. Because the dataset is large, classical models are trained directly on the training set and tested on the test set, without using k-fold validation.

The images are converted into vectors of 784 elements (28 × 28 pixels), with values from 0 to 255. Three versions of the dataset are considered:

1. Raw byte values (0–255)
2. Scaled data to [0, 1) by dividing by 256
3. Normalized data, where each pixel has its mean subtracted and is divided by its standard deviation


In [ ]:
# MNIST experiments (fixed)
import time
import numpy as np
from sklearn.neighbors import NearestCentroid, KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn import decomposition
from sklearn.datasets import fetch_openml

def load_mnist_data(fashion=False):
    """Load MNIST digits or Fashion-MNIST (tries OpenML, then keras fallback).
       Returns: x_train, y_train, x_test, y_test (float32 features scaled 0-1).
    """
    if not fashion:
        dataset_name = "MNIST (mnist_784)"
        data = fetch_openml("mnist_784", version=1, as_frame=False)
        X = data["data"].astype(np.float32)
        y = data["target"].astype(np.int64)
    else:
        dataset_name = "Fashion-MNIST"
        try:
            data = fetch_openml("Fashion-MNIST", version=1, as_frame=False)
            X = data["data"].astype(np.float32)
            y = data["target"].astype(np.int64)
        except Exception:
            # fallback to keras (if installed)
            try:
                from tensorflow.keras.datasets import fashion_mnist
            except Exception as e:
                raise RuntimeError(
                    "Could not fetch Fashion-MNIST from OpenML and keras is not available. "
                    "Install tensorflow or ensure OpenML dataset is accessible."
                ) from e
            (xtr, ytr), (xte, yte) = fashion_mnist.load_data()
            X = np.vstack([xtr.reshape(len(xtr), -1), xte.reshape(len(xte), -1)]).astype(np.float32)
            y = np.concatenate([ytr, yte]).astype(np.int64)

    # Normalize pixel values to [0,1]
    # Some openml versions store values 0..255; dividing is safe either way.
    X /= 255.0

    n = X.shape[0]
    # Standard MNIST split: 60k train / 10k test if available; otherwise use ~85/15 split
    if (not fashion) and (n >= 70000):
        train_size = 60000
    else:
        train_size = int(n * 0.857142857)  # ~60k/70k ratio

    x_train = X[:train_size]
    y_train = y[:train_size]
    x_test = X[train_size:]
    y_test = y[train_size:]

    # Print summary
    print(f"Dataset: {dataset_name}")
    print(f"Training samples: {len(x_train)}, Test samples: {len(x_test)}")
    print(f"Features: {x_train.shape[1]} (28x28 images flattened)" )
    print(f"Classes: {len(np.unique(y))}")
    if fashion:
        class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
                       'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
        print(f"Class names: {class_names}")
    else:
        print("Classes: 0-9 (digits)")
    print()

    return x_train, y_train, x_test, y_test

def run(x_train, y_train, x_test, y_test, clf):
    """Fit clf, predict, print accuracy and timing. Returns accuracy."""
    t0 = time.time()
    clf.fit(x_train, y_train)
    fit_time = time.time() - t0

    t1 = time.time()
    preds = clf.predict(x_test)
    predict_time = time.time() - t1

    acc = float(np.mean(preds == y_test))
    # print single-line result (this function is usually called after a print(..., end=''))
    print(f"{acc:.4f}  (fit: {fit_time:.2f}s, predict: {predict_time:.2f}s)")
    return acc

def train(x_train, y_train, x_test, y_test):
    print("    Nearest centroid          : ", end='')
    run(x_train, y_train, x_test, y_test, NearestCentroid())

    print("    k-NN classifier (k=3)     : ", end='')
    run(x_train, y_train, x_test, y_test, KNeighborsClassifier(n_neighbors=3))

    print("    k-NN classifier (k=7)     : ", end='')
    run(x_train, y_train, x_test, y_test, KNeighborsClassifier(n_neighbors=7))

    print("    Naive Bayes (Gaussian)    : ", end='')
    run(x_train, y_train, x_test, y_test, GaussianNB())

    print("    Decision tree             : ", end='')
    run(x_train, y_train, x_test, y_test, DecisionTreeClassifier())

    print("    Random forest (trees=  5) : ", end='')
    run(x_train, y_train, x_test, y_test, RandomForestClassifier(n_estimators=5))

    print("    Random forest (trees= 50) : ", end='')
    run(x_train, y_train, x_test, y_test, RandomForestClassifier(n_estimators=50))

    print("    Random forest (trees=500) : ", end='')
    run(x_train, y_train, x_test, y_test, RandomForestClassifier(n_estimators=500))

    print("    Random forest (trees=1000): ", end='')
    run(x_train, y_train, x_test, y_test, RandomForestClassifier(n_estimators=1000))

    print("    LinearSVM (C=0.01)        : ", end='')
    run(x_train, y_train, x_test, y_test, LinearSVC(C=0.01, max_iter=2000))

    print("    LinearSVM (C=0.1)         : ", end='')
    run(x_train, y_train, x_test, y_test, LinearSVC(C=0.1, max_iter=2000))

    print("    LinearSVM (C=1.0)         : ", end='')
    run(x_train, y_train, x_test, y_test, LinearSVC(C=1.0, max_iter=2000))

    print("    LinearSVM (C=10.0)        : ", end='')
    run(x_train, y_train, x_test, y_test, LinearSVC(C=10.0, max_iter=2000))

def main():
    # SWITCH BETWEEN DATASETS: set fashion=True for Fashion-MNIST
    x_train, y_train, x_test, y_test = load_mnist_data(fashion=False)  # MNIST digits
    # x_train, y_train, x_test, y_test = load_mnist_data(fashion=True)   # Fashion-MNIST (fallback to keras if needed)

    print("Running classifier experiments...")
    print("=" * 70)
    train(x_train, y_train, x_test, y_test)

    print("\nRunning experiments with PCA (50 components)...")
    print("=" * 70)

    # Apply PCA for dimensionality reduction
    pca = decomposition.PCA(n_components=50)
    x_train_pca = pca.fit_transform(x_train)
    x_test_pca = pca.transform(x_test)

    print(f"Original features: {x_train.shape[1]}, PCA features: {x_train_pca.shape[1]}")
    print(f"Explained variance ratio: {pca.explained_variance_ratio_.sum():.4f}")
    print()

    train(x_train_pca, y_train, x_test_pca, y_test)

if __name__ == "__main__":
    main()


Dataset: MNIST (mnist_784)
Training samples: 60000, Test samples: 10000
Features: 784 (28x28 images flattened)
Classes: 10
Classes: 0-9 (digits)

Running classifier experiments...
    Nearest centroid          : 0.8203  (fit: 0.15s, predict: 0.02s)
    k-NN classifier (k=3)     : 0.9705  (fit: 0.09s, predict: 12.41s)
    k-NN classifier (k=7)     : 0.9694  (fit: 0.08s, predict: 12.35s)
    Naive Bayes (Gaussian)    : 0.5558  (fit: 0.25s, predict: 0.17s)
    Decision tree             : 0.8793  (fit: 17.65s, predict: 0.01s)
    Random forest (trees=  5) : 0.9212  (fit: 1.87s, predict: 0.01s)
    Random forest (trees= 50) : 0.9672  (fit: 18.29s, predict: 0.10s)
    Random forest (trees=500) : 

The code uses LinearSVC instead of SVC for runtime efficiency and multiclass handling. Helper functions track both model accuracy and training/testing time, important due to the dataset’s larger size. Training is repeated for the raw, scaled, and normalized versions of the dataset.

Normalization uses the training set’s mean and standard deviation, which are also applied to test data, as these better represent the true distribution. PCA is also applied, reducing the 784 features to 15 principal components, capturing just over 33% of the variance.


In [ ]:
import numpy as np
from sklearn import decomposition
from sklearn.datasets import fetch_openml
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
import warnings
warnings.filterwarnings('ignore')

def load_mnist_data(fashion=False):
    """Load MNIST or Fashion-MNIST dataset"""
    if fashion:
        dataset = fetch_openml('Fashion-MNIST', version=1, as_frame=False, parser='auto')
    else:
        dataset = fetch_openml('mnist_784', version=1, as_frame=False, parser='auto')
    
    X, y = dataset.data, dataset.target.astype(int)
    
    # Split into train and test (MNIST: first 60k train, last 10k test)
    if fashion:
        # Fashion-MNIST is already split
        x_train, x_test = X[:60000], X[60000:]
        y_train, y_test = y[:60000], y[60000:]
    else:
        # Standard MNIST split
        x_train, x_test = X[:60000], X[60000:]
        y_train, y_test = y[:60000], y[60000:]
    
    # Normalize to [0,1] range
    x_train = x_train.astype('float64') / 255.0
    x_test = x_test.astype('float64') / 255.0
    
    return x_train, y_train, x_test, y_test

def train(x_train, y_train, x_test, y_test):
    """Train and evaluate multiple classifiers"""
    classifiers = {
        'K-NN (k=3)': KNeighborsClassifier(n_neighbors=3),
        'Decision Tree': DecisionTreeClassifier(random_state=42),
        'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
        'SVM (linear)': SVC(kernel='linear', random_state=42),
        'SVM (RBF)': SVC(kernel='rbf', random_state=42),
        'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
        'MLP': MLPClassifier(hidden_layer_sizes=(100,), random_state=42, max_iter=1000)
    }
    
    print(f"Data shape: {x_train.shape}")
    
    for name, clf in classifiers.items():
        # Use cross-validation on training set
        scores = cross_val_score(clf, x_train, y_train, cv=3, scoring='accuracy')
        
        # Also train on full training set and evaluate on test set
        clf.fit(x_train, y_train)
        test_score = clf.score(x_test, y_test)
        
        print(f"{name:20} | CV Acc: {scores.mean():.4f} (+/- {scores.std() * 2:.4f}) | Test Acc: {test_score:.4f}")
    print()

def main():
    # SWITCH BETWEEN DATASETS: set fashion=True for Fashion-MNIST
    print("=" * 60)
    print("MNIST DIGITS DATASET")
    print("=" * 60)
    x_train, y_train, x_test, y_test = load_mnist_data(fashion=False)  # MNIST digits
    
    # Convert back to [0,255] range (integers but stored as float64 for consistency)
    x_train_255 = (x_train * 255.0).astype("float64")
    x_test_255 = (x_test * 255.0).astype("float64")

    print("Models trained on raw [0,255] images:")
    train(x_train_255, y_train, x_test_255, y_test)

    print("Models trained on raw [0,1] images:")
    train(x_train, y_train, x_test, y_test)

    # Normalize by mean and std of training set
    m = x_train_255.mean(axis=0)
    s = x_train_255.std(axis=0) + 1e-8
    x_ntrain = (x_train_255 - m) / s
    x_ntest  = (x_test_255 - m) / s

    print("Models trained on normalized images:")
    train(x_ntrain, y_train, x_ntest, y_test)

    # PCA on normalized images (reduce to 15 features)
    pca = decomposition.PCA(n_components=15)
    pca.fit(x_ntrain)
    x_ptrain = pca.transform(x_ntrain)
    x_ptest = pca.transform(x_ntest)

    print("Models trained on first 15 PCA components of normalized images:")
    train(x_ptrain, y_train, x_ptest, y_test)
    
    # Optional: Also run for Fashion-MNIST
    print("\n" + "=" * 60)
    print("FASHION-MNIST DATASET")
    print("=" * 60)
    x_train_f, y_train_f, x_test_f, y_test_f = load_mnist_data(fashion=True)   # Fashion-MNIST
    
    x_train_f_255 = (x_train_f * 255.0).astype("float64")
    x_test_f_255 = (x_test_f * 255.0).astype("float64")
    
    print("Models trained on raw [0,255] images:")
    train(x_train_f_255, y_train_f, x_test_f_255, y_test_f)


if __name__ == "__main__":
    main()

MNIST DIGITS DATASET
Models trained on raw [0,255] images:
Data shape: (60000, 784)


### Experimenting with PCA Components

Previously, 15 PCA components were used, representing about 33% of the dataset’s variance. To explore the effect of PCA further, the number of components is varied from 10 to 780, and three models are trained for each setting: Gaussian naive Bayes, random forest (50 trees), and linear SVM (C = 1.0). This process is computationally intensive and took over 10 hours on a low-end machine.


In [ ]:
# PCA Component Experiments
import time
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn import decomposition
from sklearn.datasets import fetch_openml

def load_mnist_data(fashion=False):
    """Load MNIST digits or Fashion-MNIST dataset"""
    if fashion:
        # Load Fashion-MNIST dataset
        print("Loading Fashion-MNIST dataset...")
        X, y = fetch_openml('Fashion-MNIST', version=1, return_X_y=True, as_frame=False)
        dataset_name = "Fashion-MNIST"
    else:
        # Load MNIST digits dataset  
        print("Loading MNIST digits dataset...")
        X, y = fetch_openml('mnist_784', version=1, return_X_y=True, as_frame=False)
        dataset_name = "MNIST digits"
    
    # Convert to proper data types
    X = X.astype(np.float64)
    y = y.astype(np.int32)
    
    # Use standard train/test split (first 60000 for train, last 10000 for test)
    x_train = X[:60000]
    x_test = X[60000:]
    y_train = y[:60000] 
    y_test = y[60000:]
    
    print(f"Dataset: {dataset_name}")
    print(f"Training samples: {len(x_train)}, Test samples: {len(x_test)}")
    print(f"Features: {x_train.shape[1]} (28x28 images)")
    print()
    
    return x_train, y_train, x_test, y_test

def run(x_train, y_train, x_test, y_test, clf):
    """Train classifier and measure time + accuracy"""
    s = time.time()
    clf.fit(x_train, y_train)
    e_train = time.time() - s 
    s = time.time()
    score = clf.score(x_test, y_test)
    e_test = time.time() - s 
    return [score, e_train, e_test]

def main():
    # SWITCH BETWEEN DATASETS: Uncomment one of the following lines
    x_train, y_train, x_test, y_test = load_mnist_data(fashion=False)  # MNIST digits
    # x_train, y_train, x_test, y_test = load_mnist_data(fashion=True)   # Fashion-MNIST
    
    # Normalize the data (z-score normalization)
    m = x_train.mean(axis=0)
    s = x_train.std(axis=0) + 1e-8
    x_ntrain = (x_train - m) / s 
    x_ntest = (x_test - m) / s 
    
    print("Running PCA component analysis...")
    print("Testing components from 10 to 780 (78 different values)")
    print()

    n = 78
    pcomp = np.linspace(10, 780, n, dtype="int16")
    nb = np.zeros((n, 4))  # [n_components, score, train_time, test_time]
    rf = np.zeros((n, 4))
    sv = np.zeros((n, 4))
    tv = np.zeros((n, 2))  # [n_components, explained_variance_ratio]

    print("Progress:")
    for i, p in enumerate(pcomp):
        print(f"Testing {p} components... ({i+1}/{n})", end=" ")
        
        pca = decomposition.PCA(n_components=p)
        pca.fit(x_ntrain)
        xtrain = pca.transform(x_ntrain)
        xtest = pca.transform(x_ntest)
        tv[i, :] = [p, pca.explained_variance_ratio_.sum()]
        
        # Test Naive Bayes
        sc, etrn, etst = run(xtrain, y_train, xtest, y_test, GaussianNB())
        nb[i, :] = [p, sc, etrn, etst]
        
        # Test Random Forest
        sc, etrn, etst = run(xtrain, y_train, xtest, y_test, RandomForestClassifier(n_estimators=50))
        rf[i, :] = [p, sc, etrn, etst]
        
        # Test Linear SVM
        sc, etrn, etst = run(xtrain, y_train, xtest, y_test, LinearSVC(C=1.0, max_iter=2000))
        sv[i, :] = [p, sc, etrn, etst]
        
        print(f"Done. (Variance explained: {tv[i, 1]:.3f})")

    # Save results to local files
    print("\nSaving results...")
    np.save("mnist_pca_tv.npy", tv)  # Total variance explained
    np.save("mnist_pca_nb.npy", nb)  # Naive Bayes results
    np.save("mnist_pca_rf.npy", rf)  # Random Forest results
    np.save("mnist_pca_sv.npy", sv)  # Linear SVM results
    
    print("Results saved to:")
    print("  - mnist_pca_tv.npy: [n_components, explained_variance_ratio]")
    print("  - mnist_pca_nb.npy: [n_components, score, train_time, test_time] for Naive Bayes")
    print("  - mnist_pca_rf.npy: [n_components, score, train_time, test_time] for Random Forest")
    print("  - mnist_pca_sv.npy: [n_components, score, train_time, test_time] for Linear SVM")
    
    # Print summary statistics
    print("\nSummary - Best performance by number of components:")
    print("Naive Bayes:")
    best_nb_idx = np.argmax(nb[:, 1])
    print(f"  Best: {nb[best_nb_idx, 0]:.0f} components, score: {nb[best_nb_idx, 1]:.4f}")
    
    print("Random Forest:")
    best_rf_idx = np.argmax(rf[:, 1])
    print(f"  Best: {rf[best_rf_idx, 0]:.0f} components, score: {rf[best_rf_idx, 1]:.4f}")
    
    print("Linear SVM:")
    best_sv_idx = np.argmax(sv[:, 1])
    print(f"  Best: {sv[best_sv_idx, 0]:.0f} components, score: {sv[best_sv_idx, 1]:.4f}")


if __name__ == "__main__":
    main()


Loading MNIST digits dataset...
Dataset: MNIST digits
Training samples: 60000, Test samples: 10000
Features: 784 (28x28 images)

Running PCA component analysis...
Testing components from 10 to 780 (78 different values)

Progress:
Testing 10 components... (1/78) Done. (Variance explained: 0.277)
Testing 20 components... (2/78) Done. (Variance explained: 0.381)
Testing 30 components... (3/78) Done. (Variance explained: 0.452)
Testing 40 components... (4/78) Done. (Variance explained: 0.506)
Testing 50 components... (5/78) Done. (Variance explained: 0.551)
Testing 60 components... (6/78) Done. (Variance explained: 0.589)
Testing 70 components... (7/78) Done. (Variance explained: 0.623)
Testing 80 components... (8/78) Done. (Variance explained: 0.653)
Testing 90 components... (9/78) 

## Classical Model Summary

The chapter concludes with a summary of pros and cons for the six classical models discussed:

### Nearest Centroid

- **Pros:** Simple implementation, fast training, low memory use, supports multiclass classification, fast inference.
- **Cons:** Assumes each class forms a tight cluster in feature space, often too simplistic for complex data. Variants with multiple centroids per class can improve performance.

### k-Nearest Neighbors (k-NN)

- **Pros:** No explicit training required, works well with large datasets, supports multiclass classification naturally.
- **Cons:** Slow inference because distances must be computed for every training sample, even with optimized algorithms.

### Naive Bayes

- **Pros:** Fast to train and classify, supports multiclass problems, works for both discrete and continuous features.
- **Cons:** Assumes feature independence, which is rarely true in practice. Continuous features often require additional distributional assumptions (e.g., Gaussian).

### Decision Trees

- **Pros:** Fast training and inference, interpretable, supports multiclass and mixed feature types, can justify decisions with a clear path from root to leaf.
- **Cons:** Prone to overfitting, interpretability decreases with tree size, requires balancing tree depth against accuracy.

### Random Forests

- **Pros:** Robust to overfitting, supports multiclass problems, reasonably fast to train and infer, less sensitive to feature scaling, accuracy improves with more trees.
- **Cons:** Harder to interpret than single decision trees, inference time scales linearly with the number of trees, stochastic performance can vary slightly between trainings.

### Support Vector Machines (SVMs)

- **Pros:** Can achieve excellent performance, fast inference after training.
- **Cons:** Multiclass requires multiple models, only supports continuous features, sensitive to feature scaling, difficult to train on large datasets with non-linear kernels, requires careful hyperparameter tuning.

## When to Use Classical Models

Classical models remain appropriate under certain conditions:

1. **Small datasets:** They perform well when there are only tens or hundreds of examples, unlike deep learning models that require larger datasets.
2. **Limited computational resources:** Simple models (nearest centroid, naive Bayes, decision trees, SVMs) are feasible on low-power devices; k-NN may be too slow unless the dataset is small.
3. **Explainability:** Models like decision trees, k-NN, nearest centroid, and naive Bayes can explain their predictions, unlike deep neural networks.
4. **Vector inputs without structure:** When features are independent and unstructured (not spatially correlated as in images), classical models are suitable.

These are rules of thumb, not hard rules. Deep learning could be used even when these conditions apply, but classic models may provide sufficient performance with less complexity.


